In [1]:
import pandas as pd
import matplotlib.pyplot as pl

In [2]:
housing_data = pd.read_csv("C:\\Users\\sarth\\Documents\\ScikitLearn\\Datasets\\housing_csv\\housing.csv")
housing_data.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
13039,-121.15,38.68,6.0,9798.0,1551.0,4583.0,1494.0,5.0159,189600.0,INLAND
19269,-122.73,38.43,15.0,3265.0,690.0,1629.0,629.0,3.7132,167600.0,<1H OCEAN
10366,-117.68,33.60,19.0,3913.0,460.0,1646.0,454.0,7.2147,303900.0,<1H OCEAN
19889,-119.16,36.31,7.0,2946.0,664.0,1608.0,622.0,1.6829,80200.0,INLAND
1307,-121.83,37.99,23.0,1970.0,296.0,935.0,279.0,4.4853,145900.0,INLAND

In [3]:
housing_data.dropna()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY
11,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0,NEAR BAY
12,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0,NEAR BAY
13,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0,NEAR BAY
14,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0,NEAR BAY
15,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0,NEAR BAY
16,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0,NEAR BAY
17,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0,NEAR BAY
18,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0,NEAR BAY
19,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0,NEAR BAY
20,-122.27,37.85,40.0,751.0,184.0,409.0,166.0,1.3578,147500.0,NEAR BAY
21,-122.27,37.85,42.0,1639.0,367.0,929.0,366.0,1.7135,159800.0,NEAR BAY
22,-122.27,37.84,52.0,2436.0,541.0,1015.0,478.0,1.7250,113900.0,NEAR BAY
23,-122.27,37.84,52.0,1688.0,337.0,853.0,325.0,2.1806,99700.0,NEAR BAY
24,-122.27,37.84,52.0,2224.0,437.0,1006.0,422.0,2.6000,132600.0,NEAR BAY
25,-122.28,37.85,41.0,535.0,123.0,317.0,119.0,2.4038,107500.0,NEAR BAY
26,-122.28,37.85,49.0,1130.0,244.0,607.0,239.0,2.4597,93800.0,NEAR BAY
27,-122.28,37.85,52.0,1898.0,421.0,1102.0,397.0,1.8080,105500.0,NEAR BAY
28,-122.28,37.84,50.0,2082.0,492.0,1131.0,473.0,1.6424,108900.0,NEAR BAY
29,-122.28,37.84,52.0,729.0,160.0,395.0,155.0,1.6875,132000.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20610,-121.56,39.10,28.0,2130.0,484.0,1195.0,439.0,1.3631,45500.0,INLAND
20611,-121.55,39.10,27.0,1783.0,441.0,1163.0,409.0,1.2857,47000.0,INLAND
20612,-121.56,39.08,26.0,1377.0,289.0,761.0,267.0,1.4934,48300.0,INLAND
20613,-121.55,39.09,31.0,1728.0,365.0,1167.0,384.0,1.4958,53400.0,INLAND
20614,-121.54,39.08,26.0,2276.0,460.0,1455.0,474.0,2.4695,58000.0,INLAND
20615,-121.54,39.08,23.0,1076.0,216.0,724.0,197.0,2.3598,57500.0,INLAND
20616,-121.53,39.08,15.0,1810.0,441.0,1157.0,375.0,2.0469,55100.0,INLAND
20617,-121.53,39.06,20.0,561.0,109.0,308.0,114.0,3.3021,70800.0,INLAND
20618,-121.55,39.06,25.0,1332.0,247.0,726.0,226.0,2.2500,63400.0,INLAND
20619,-121.56,39.01,22.0,1891.0,340.0,1023.0,296.0,2.7303,99100.0,INLAND
20620,-121.48,39.05,40.0,198.0,41.0,151.0,48.0,4.5625,100000.0,INLAND
20621,-121.47,39.01,37.0,1244.0,247.0,484.0,157.0,2.3661,77500.0,INLAND
20622,-121.44,39.00,20.0,755.0,147.0,457.0,157.0,2.4167,67000.0,INLAND
20623,-121.37,39.03,32.0,1158.0,244.0,598.0,227.0,2.8235,65500.0,INLAND
20624,-121.41,39.04,16.0,1698.0,300.0,731.0,291.0,3.0739,87200.0,INLAND
20625,-121.52,39.12,37.0,102.0,17.0,29.0,14.0,4.1250,72000.0,INLAND
20626,-121.43,39.18,36.0,1124.0,184.0,504.0,171.0,2.1667,93800.0,INLAND
20627,-121.32,39.13,5.0,358.0,65.0,169.0,59.0,3.0000,162500.0,INLAND
20628,-121.48,39.10,19.0,2043.0,421.0,1018.0,390.0,2.5952,92400.0,INLAND
20629,-121.39,39.12,28.0,10035.0,1856.0,6912.0,1818.0,2.0943,108300.0,INLAND
20630,-121.32,39.29,11.0,2640.0,505.0,1257.0,445.0,3.5673,112000.0,INLAND
20631,-121.40,39.33,15.0,2655.0,493.0,1200.0,432.0,3.5179,107200.0,INLAND
20632,-121.45,39.26,15.0,2319.0,416.0,1047.0,385.0,3.1250,115600.0,INLAND
20633,-121.53,39.19,27.0,2080.0,412.0,1082.0,382.0,2.5495,98300.0,INLAND
20634,-121.56,39.27,28.0,2332.0,395.0,1041.0,344.0,3.7125,116800.0,INLAND
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
housing_data = housing_data.dropna()

In [5]:
housing_data.shape

(20433, 10)

In [6]:
housing_data = housing_data.drop(housing_data.loc[housing_data["median_house_value"]==500001].index)

In [7]:
housing_data.shape

(19475, 10)

In [8]:
housing_data["median_house_value"].median()

173800.0

In [9]:
housing_data["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [10]:
housing_data =pd.get_dummies(housing_data, columns=["ocean_proximity"])

In [11]:
housing_data.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
20138,-119.05,34.40,50.0,1236.0,282.0,1079.0,257.0,2.6991,181300.0,1,0,0,0,0
8366,-118.35,33.97,26.0,3832.0,1074.0,2340.0,904.0,2.6734,143400.0,1,0,0,0,0
13103,-121.34,38.44,14.0,3205.0,465.0,1439.0,456.0,5.7452,240900.0,0,1,0,0,0
10172,-117.98,33.86,25.0,1025.0,266.0,726.0,183.0,3.8750,137500.0,1,0,0,0,0
10388,-117.64,33.59,4.0,3274.0,383.0,1312.0,390.0,8.1611,348000.0,1,0,0,0,0

In [12]:
median = housing_data["median_house_value"].median()
median

173800.0

In [13]:
housing_data["above_median"] = (housing_data["median_house_value"] - median)>0

In [14]:
housing_data.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN,above_median
11778,-121.29,38.76,12.0,1198.0,174.0,443.0,170.0,6.0097,187500.0,0,1,0,0,0,True
18856,-122.27,41.23,40.0,1958.0,386.0,725.0,331.0,2.1898,65500.0,0,1,0,0,0,False
20018,-119.04,36.09,15.0,2288.0,401.0,1238.0,429.0,3.0278,77400.0,0,1,0,0,0,False
17657,-121.89,37.28,35.0,2418.0,375.0,988.0,374.0,6.0936,365400.0,1,0,0,0,0,True
10408,-117.58,33.65,4.0,2000.0,422.0,833.0,386.0,5.7709,190300.0,1,0,0,0,0,True

In [15]:
X = housing_data.drop(["median_house_value","above_median"],axis=1)
Y=housing_data["above_median"]

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

In [17]:
x_train.shape,x_test.shape

((15580, 13), (3895, 13))

In [18]:
y_train.shape,y_test.shape

((15580,), (3895,))

In [19]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(solver="liblinear").fit(x_train,y_train)

In [20]:
print("Training Score:", logistic_model.score(x_train,y_train))

Training Score: 0.8197047496790757

In [21]:
y_pred = logistic_model.predict(x_test)

In [22]:
diff_pred_test = pd.DataFrame({"predicted":y_pred, "actual":y_test})
diff_pred_test

       predicted  actual
5788        True    True
15917      False    True
3168       False   False
1546        True    True
19627      False   False
777         True    True
6862        True    True
17187       True    True
15063      False   False
18217       True    True
891         True    True
9259       False   False
3209       False   False
12062      False   False
20518      False   False
10568       True    True
1143       False   False
2394       False   False
816         True    True
16518      False   False
8722        True    True
9856        True    True
4805       False   False
3094       False   False
3756        True    True
15916       True    True
10277       True    True
3847        True    True
11775      False   False
15711       True    True
...          ...     ...
257        False   False
11430       True    True
818        False   False
12075      False   False
18521       True    True
9855        True    True
16856       True    True
17748       True    True
3956        True    True
16272      False   False
180         True   False
1145       False   False
19552      False   False
4957        True   False
13674      False   False
9781       False   False
16054       True    True
10066      False   False
919         True    True
15912       True    True
7674        True   False
2900       False   False
8782        True    True
10812      False    True
15738      False   False
10067      False   False
16831       True    True
16541      False   False
15842       True    True
2411       False   False

[3895 rows x 2 columns]

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
print("Testing score:", accuracy_score(y_test, y_pred))

Testing score: 0.8233632862644416